/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CharacterCard: typeof import('./src/components/CharacterCard.vue')['default']
    CollapsiblePanel: typeof import('./src/components/CollapsiblePanel.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
